id: A83A88544
base_file: f4DE2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 07:04:10.978397
  last_modified_at: 2022-05-31 07:04:10.978403
