id: A83A88544
base_file: fD197.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 07:04:10.982909
  last_modified_at: 2022-05-31 07:04:10.982919
